(function(){
const API='https://kvqxclmlpxqmefmmtodw.supabase.co/functions/v1/dashboard-data-v2';
const iframe=document.getElementById('app');let W=null;
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const num=v=>{const n=Number(String(v??'').replace(/,/g,''));return Number.isFinite(n)?n:0};
const INR=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(num(v));
const clean=v=>String(v??'').trim(), lower=v=>clean(v).toLowerCase();
const authHeaders=()=>{const t=window.parent?.__RBAC_SESSION?.access_token;return t?{Authorization:'Bearer '+t}:{} };
const dateKey=v=>{if(typeof W?.dateKey==='function')return W.dateKey(v);const s=clean(v);if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;if(/^\d{8}$/.test(s))return `${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}`;return ''};
function ik(r){const t=clean(r.tab_id??r.tabId);if(t)return 'tab:'+t;const s=clean(r.session_id??r.sessionId),d=dateKey(r.date??r.dt??r.Date);return s?'session:'+s+'|date:'+d:''}
function wk(r){const e=lower(r.agent_email??r['Agent EMail']??r['Agent Email']),d=dateKey(r.date??r.Date),s=clean(r.slot_start_time??r['Slot Start Time']),z=clean(r.slot_end_time??r['Slot End Time']);return e&&d&&s&&z?e+'|'+d+'|'+s+'|'+z:''}
function merge(oldRows,newRows,keyFn){const m=new Map(),seen=new Set();oldRows.forEach(r=>{const k=keyFn(r);if(k)m.set(k,r)});let inserted=0,updated=0,rejected=0;newRows.forEach(r=>{const k=keyFn(r);if(!k){rejected++;return}if(m.has(k)){m.set(k,{...m.get(k),...r});if(!seen.has(k)){updated++;seen.add(k)}}else{m.set(k,r);inserted++}});return{rows:[...m.values()],inserted,updated,rejected}}
function classify(c,l){if(c&&l)return'Mixed';if(c)return'Interaction / Daily Update';if(l)return'Workforce / Login Hours';return'Unknown / Invalid'}
function stat(a){const rated=a.filter(x=>['DSAT','CSAT','Neutral'].includes(x.rating_bucket)),ds=a.filter(x=>x.rating_bucket==='DSAT'),cs=a.filter(x=>x.rating_bucket==='CSAT');return{inflow:a.length,frt:a.length?+(a.reduce((s,x)=>s+num(x.agent_frt),0)/a.length).toFixed(2):0,aht:a.length?+(a.reduce((s,x)=>s+num(x.ht),0)/a.length).toFixed(2):0,dsat:rated.length?+(ds.length/rated.length*100).toFixed(2):0,csat:rated.length?+(cs.length/rated.length*100).toFixed(2):0,rated:rated.length,refund:a.reduce((s,x)=>s+num(x.refund_value??x.total_refunded_amount),0),refundChats:a.filter(x=>num(x.refund_chat_flag)>0).length,delay:a.length?+(a.reduce((s,x)=>s+num(x.order_delay_mins),0)/a.length).toFixed(2):0}}
async function centralLoad(){const r=await fetch(API,{cache:'no-store'}),j=await r.json();if(!r.ok||j.error)throw Error(j.error||'Central dataset unavailable');W.DB.customer=j.payload?.customer||[];W.DB.login=j.payload?.login||[];W.DB.agents=j.payload?.agents||{};W.DB.meta=j.payload?.meta||W.DB.meta;W.DB.upload=j.metadata||{};W.DB.history=j.history||[];const st=W.document.getElementById('status');if(st)st.textContent=j.ready?'Data Status: Ready':'Data Status: No Dataset';return j}
async function centralUpload(){const fs=[...W.document.querySelectorAll('#customerFiles,#loginFiles,#customerFile,#loginFile')].flatMap(x=>[...(x.files||[])]),files=[...new Map(fs.map(f=>[f.name+'|'+f.size+'|'+f.lastModified,f])).values()];if(!files.length){alert('Please select at least one XLSX/XLS/CSV file.');return}const msg=W.document.getElementById('uploadMsg');if(msg)msg.textContent='Detecting, validating and merging files…';let incomingC=[],incomingL=[],agents={},processed=[];for(const f of files){const wb=W.XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:false});let c=[],l=[];try{const p=W.parseCustomer(wb);if(p?.C?.length){c=p.C;Object.assign(agents,p.names||p.agents||{})}}catch(e){console.warn('Customer parse',f.name,e)}try{const q=W.parseLogin(wb);if(q?.length)l=q}catch(e){console.warn('Login parse',f.name,e)}if(c.length||l.length)processed.push({name:f.name,type:classify(c.length,l.length),rows:c.length+l.length}),incomingC.push(...c),incomingL.push(...l)}if(!incomingC.length&&!incomingL.length){if(msg)msg.textContent='File type could not be detected or required columns are missing. Existing dashboard data was not changed.';return}const oldC=W.DB.customer||[],oldL=W.DB.login||[],cm=merge(oldC,incomingC,ik),lm=merge(oldL,incomingL,wk),payload={customer:cm.rows,login:lm.rows,agents:{...(W.DB.agents||{}),...agents},meta:W.DB.meta||{expectedLoginHours:8,expectedBreakHours:1}},metadata={fileNames:files.map(f=>f.name),uploadedBy:window.parent?.__RBAC_PROFILE?.email||'dashboard user',meta:payload.meta};if(msg)msg.textContent=`Merging ${incomingC.length.toLocaleString()} interaction + ${incomingL.length.toLocaleString()} workforce rows…`;const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify({customer:payload.customer,login:payload.login,agents:payload.agents,metadata})}),j=await r.json();if(!r.ok||j.error)throw Error(j.error||'Upload failed. Existing dashboard data was not changed.');await centralLoad();selectedNode='';selectedNodeAgent='';renderOuter()}
let selectedNode='',selectedNodeAgent='',nodeView='overall';
function nodeUI(){const base=W.DB.customer||[],nodes=[...new Set(base.map(x=>clean(x.node)).filter(Boolean))].sort();if(selectedNode&&!nodes.includes(selectedNode))selectedNode='';const g=selectedNode?base.filter(x=>clean(x.node)===selectedNode):base,by={};g.forEach(x=>{const e=lower(x.agent_email);if(e)(by[e]??=[]).push(x)});const ar=Object.entries(by).map(([e,z])=>({e,name:W.DB.agents?.[e]||z[0]?.Name||e,s:stat(z),node:[...new Set(z.map(x=>clean(x.node)).filter(Boolean))].join(', ')}));if(selectedNodeAgent&&!ar.some(x=>x.e===selectedNodeAgent))selectedNodeAgent='';const shown=selectedNodeAgent?g.filter(x=>lower(x.agent_email)===selectedNodeAgent):g,login=(W.DB.login||[]).filter(x=>(!selectedNode||g.some(r=>lower(r.agent_email)===lower(x.agent_email)))&&(!selectedNodeAgent||lower(x.agent_email)===selectedNodeAgent)),online=login.reduce((z,x)=>z+num(x['Online Time']),0)/3600,res=login.reduce((z,x)=>z+num(x['Chat Resolved']),0),cnt=login.reduce((z,x)=>z+num(x['Chat Count']),0),s=stat(shown),k=W.kpis(s,{online,res,count:cnt});const heads=nodeView==='agent'?['Agent','Node','Inflow','AHT','FRT','CSAT','DSAT','Refund']:['Agent','Inflow','AHT','FRT','CSAT','DSAT','Refund'];const tr=ar.map(x=>nodeView==='agent'?`<tr><td>${esc(x.name)}</td><td>${esc(x.node)}</td><td>${x.s.inflow}</td><td>${x.s.aht} min</td><td>${x.s.frt} sec</td><td>${x.s.csat}%</td><td>${x.s.dsat}%</td><td>${INR(x.s.refund)}</td></tr>`:`<tr><td>${esc(x.name)}</td><td>${x.s.inflow}</td><td>${x.s.aht} min</td><td>${x.s.frt} sec</td><td>${x.s.csat}%</td><td>${x.s.dsat}%</td><td>${INR(x.s.refund)}</td></tr>`).join('');return`<div class="pagehead"><h2>Node Intelligence</h2><p>Central dataset • live node and agent filtering</p></div><div class="card" style="padding:14px;margin-bottom:12px"><div class="selectline"><b>Node</b><select id="centralNode"><option value="">All Nodes</option>${nodes.map(x=>`<option ${x===selectedNode?'selected':''} value="${esc(x)}">${esc(x)}</option>`).join('')}${nodeView==='agent'?`</select><b>Agent</b><select id="centralNodeAgent"><option value="">All Agents</option>${ar.map(x=>`<option ${x.e===selectedNodeAgent?'selected':''} value="${esc(x.e)}">${esc(x.name)}</option>`).join('')}`:''}</select></div></div><div class="tabs"><button class="tab ${nodeView==='overall'?'active':''}" id="centralOverall">Overall View</button><button class="tab ${nodeView==='agent'?'active':''}" id="centralAgent">Agent View</button></div>${k}<div class="grid2"><div class="card chartcard"><div id="ntrend" class="chart"></div></div><div class="card chartcard"><div id="nagent" class="chart"></div></div></div><div class="section"><h2>${esc(selectedNode||'All Nodes')} — ${nodeView==='agent'?'Agent View':'Overall View'}</h2></div>${W.table(heads,tr)}<div class="section"><h2>Detailed Records</h2></div>${W.rawTable(shown,100)}`}
function uploadUI(){const h=W.DB.history||[];return`<div class="pagehead"><h2>Upload Data</h2><p>Admin-only upload. New files are merged with the existing persistent dataset; unrelated historical data is preserved.</p></div><div class="card upload"><div class="uploadgrid"><div class="uploadbox"><b>Customer / Daily Update</b><input id="customerFiles" type="file" multiple accept=".xlsx,.xls,.csv"><small class="muted">Interaction, FRT, AHT, inflow, refund, ratings, calls, delay, node &amp; agent data</small></div><div class="uploadbox"><b>Login / Workforce</b><input id="loginFiles" type="file" multiple accept=".xlsx,.xls,.csv"><small class="muted">Login, break, chat count, resolved and workforce slots</small></div></div><div class="drop"><b>Drag &amp; drop XLSX/XLS/CSV files</b><span class="muted">Dataset type is detected from the file schema.</span></div><div class="actions"><button class="btn primary" id="centralUploadBtn">Process &amp; Merge Centrally</button><button class="btn" onclick="go('/overview')">View Dashboard</button></div><div id="uploadMsg" class="notice" style="margin-top:12px">${W.DB.upload?.file_name?`Last upload: ${esc(W.DB.upload.file_name)}`:'No central dataset uploaded yet.'}</div><div class="section"><h2>Central Dataset Status</h2></div><div class="detailgrid"><div class="card detail"><small>Interaction Rows</small><strong>${(W.DB.customer||[]).length.toLocaleString()}</strong></div><div class="card detail"><small>Workforce Rows</small><strong>${(W.DB.login||[]).length.toLocaleString()}</strong></div><div class="card detail"><small>Date Range</small><strong>${W.DB.upload?.date_min?W.DB.upload.date_min+' – '+W.DB.upload.date_max:'—'}</strong></div><div class="card detail"><small>Last Updated</small><strong>${W.DB.upload?.last_updated?new Date(W.DB.upload.last_updated).toLocaleString():'—'}</strong></div></div><div class="section"><h2>Upload History</h2></div>${h.length?W.table(['File','Type','Rows','Inserted','Updated','Rejected','Status','Uploaded'],h.map(x=>`<tr><td>${esc(x.file_name||'')}</td><td>${esc(x.dataset_type||'')}</td><td>${num(x.rows_processed).toLocaleString()}</td><td>${num(x.inserted_rows).toLocaleString()}</td><td>${num(x.updated_rows).toLocaleString()}</td><td>${num(x.rejected_rows).toLocaleString()}</td><td>${esc(x.status||'')}</td><td>${x.uploaded_at?new Date(x.uploaded_at).toLocaleString():''}</td></tr>`).join('')):'<div class="notice">No upload history available.</div>'}</div>`}
function showUpload(){if(window.parent?.__RBAC_PROFILE?.role!=='ADMIN'){W.document.getElementById('app').innerHTML='<div class="notice dangerbox">Admin access required for Upload Data.</div>';return}const app=W.document.getElementById('app');app.innerHTML=uploadUI();W.document.getElementById('centralUploadBtn').onclick=()=>centralUpload().catch(e=>{console.error(e);W.document.getElementById('uploadMsg').textContent='Upload failed. Existing dashboard data was not changed. '+e.message})}
function showNode(){const app=W.document.getElementById('app');app.innerHTML=nodeUI();const n=W.document.getElementById('centralNode');if(n)n.onchange=()=>{selectedNode=n.value;selectedNodeAgent='';showNode()};const a=W.document.getElementById('centralNodeAgent');if(a)a.onchange=()=>{selectedNodeAgent=a.value;showNode()};W.document.getElementById('centralOverall').onclick=()=>{nodeView='overall';selectedNodeAgent='';showNode()};W.document.getElementById('centralAgent').onclick=()=>{nodeView='agent';selectedNodeAgent='';showNode()}}
function patchNav(){W.document.querySelectorAll('a[href^="/"]').forEach(a=>{if(a.dataset.centralPatched)return;a.dataset.centralPatched='1';a.addEventListener('click',e=>{e.preventDefault();const p=a.getAttribute('href');history.pushState({},'',p);renderOuter()})})}
function renderOuter(){const p=location.pathname==='/'||location.pathname==='/index.html'?'/overview':location.pathname;try{W.go(p)}catch(e){}setTimeout(()=>{if(p==='/upload')showUpload();if(p==='/node-intelligence')showNode();patchNav()},80)}
iframe.addEventListener('load',async()=>{W=iframe.contentWindow;try{await centralLoad();renderOuter();W.startUpload=centralUpload;W.processFiles=centralUpload;W.refresh=async()=>{await centralLoad();renderOuter()};patchNav()}catch(e){console.error(e)}});window.addEventListener('popstate',renderOuter);
})();