(function(){
const API='https://kvqxclmlpxqmefmmtodw.supabase.co/functions/v1/dashboard-data-v2';
let W=null;
const clean=v=>String(v??'').replace(/^\uFEFF/,'').replace(/[\u200B-\u200F\u2060]/g,'').replace(/\u00A0/g,' ').trim();
const norm=v=>clean(v).toLowerCase().replace(/[\s_\-\u2010-\u2015]+/g,'');
const alias={
 date:['date','dt'], slot_start_time:['slotstarttime'], slot_end_time:['slotendtime'], agent_email:['agentemail','email','emailid'], online_time:['onlinetime'], break_time:['breaktime'],
 chat_count:['chatcount'], chat_resolved:['chatresolved'], tl_email:['tlemail','tlemailid'], vendor_name:['vendorname','vendor'], site_name:['sitename','site']
};
const workforceRequired=['date','slot_start_time','slot_end_time','agent_email','online_time','break_time'];
const interactionRequired=['tab_id','session_id','agent_frt','ht','agent_email','node'];
function mapHeaders(headers){const out={};const used=new Set();headers.forEach(h=>{const n=norm(h);for(const [canonical,aliases] of Object.entries(alias)){if(!out[canonical]&&aliases.includes(n)){out[canonical]=h;break}}used.add(n)});return out}
function hasAll(headers,fields){const n=new Set(headers.map(norm));return fields.every(f=>{const aliases=alias[f]||[norm(f)];return aliases.some(a=>n.has(norm(a)))})}
function detect(headers){const wf=hasAll(headers,workforceRequired), ix=hasAll(headers,interactionRequired);return wf?{type:'workforce',confidence:'HIGH'}:ix?{type:'interaction',confidence:'HIGH'}:{type:'unknown',confidence:'LOW'} }
function rawRows(ws){return W.XLSX.utils.sheet_to_json(ws,{defval:null,raw:true}).map(r=>{const x={};Object.keys(r).forEach(k=>x[clean(k)]=r[k]);return x})}
function canonicalWorkforce(rows){return rows.map(r=>{const h=mapHeaders(Object.keys(r));const val=k=>h[k]!==undefined?r[h[k]]:null;return{date:W.dateKey(val('date')),slot_start_time:clean(val('slot_start_time')),slot_end_time:clean(val('slot_end_time')),agent_email:clean(val('agent_email')).toLowerCase(),online_time:val('online_time'),break_time:val('break_time'),chat_count:val('chat_count'),chat_resolved:val('chat_resolved'),tl_email:clean(val('tl_email')).toLowerCase(),vendor_name:clean(val('vendor_name')),site_name:clean(val('site_name'))}}).filter(r=>r.date&&r.agent_email&&r.slot_start_time&&r.slot_end_time)}
function diagnostic(type,headers){const missing=(type==='workforce'?workforceRequired:interactionRequired).filter(f=>!hasAll(headers,[f]));return missing}
async function readFile(f){const wb=W.XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:false,raw:true});const out={workforce:[],interaction:[],agents:{},diagnostics:[]};for(const sn of wb.SheetNames){const ws=wb.Sheets[sn], headers=(W.XLSX.utils.sheet_to_json(ws,{header:1,defval:null,raw:true})[0]||[]).map(clean).filter(Boolean);const d=detect(headers);if(d.type==='workforce'){out.workforce.push(...canonicalWorkforce(rawRows(ws)));}else if(d.type==='interaction'){try{const one=W.XLSX.utils.book_new();one.SheetNames=[];W.XLSX.utils.book_append_sheet(one,ws,sn);const p=W.parseCustomer(one);if(p&&p.C)out.interaction.push(...p.C);if(p&&p.names)Object.assign(out.agents,p.names);}catch(e){out.diagnostics.push({file:f.name,sheet:sn,type:'interaction',error:e.message})}}else{out.diagnostics.push({file:f.name,sheet:sn,type:'unknown',headers,missingWorkforce:diagnostic('workforce',headers),missingInteraction:diagnostic('interaction',headers)})}}return out}
async function fetchCentral(){const r=await fetch(API,{cache:'no-store'}),j=await r.json();if(!r.ok||j.error)throw Error(j.error||'Central dataset unavailable');if(W){W.DB.customer=j.payload?.customer||[];W.DB.login=j.payload?.login||[];W.DB.agents=j.payload?.agents||{};W.DB.meta=j.payload?.meta||W.DB.meta;W.DB.upload=j.metadata||{};const s=W.document.getElementById('status');if(s)s.textContent=j.ready?'Data Status: Ready':'Data Status: No Dataset';}return j}
function msg(t,kind){const el=W&&W.document.getElementById('uploadMsg');if(el){el.className='notice '+(kind||'');el.textContent=t}}
async function upload(){const files=[...new Map([...W.document.querySelectorAll('#customerFiles,#loginFiles,#customerFile,#loginFile')].flatMap(x=>[...(x.files||[])]).map(f=>[f.name+'|'+f.size,f])).values()];if(!files.length){msg('Please select at least one XLSX, XLS or CSV file.','dangerbox');return}msg('Scanning files and detecting dataset types…');let customer=[],login=[],agents={},unknown=[];for(const f of files){try{const x=await readFile(f);customer.push(...x.interaction);login.push(...x.workforce);Object.assign(agents,x.agents);unknown.push(...x.diagnostics.filter(d=>d.type==='unknown'));}catch(e){unknown.push({file:f.name,type:'parse_error',error:e.message})}}if(!customer.length&&!login.length){const d=unknown[0];msg(`Could not identify dataset type. ${d?`File: ${d.file}. Missing Workforce: ${(d.missingWorkforce||[]).join(', ')||'none'}. Missing Interaction: ${(d.missingInteraction||[]).join(', ')||'none'}.`:''}`,'dangerbox');return}msg(`Detected: ${login.length?`WORKFORCE (${login.length.toLocaleString()} rows)`:''}${login.length&&customer.length?' + ':''}${customer.length?`INTERACTION (${customer.length.toLocaleString()} rows)`:''}. Saving only these dataset types…`);const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer,login,agents,metadata:{fileNames:files.map(f=>f.name),uploadedBy:'dashboard user'}})}),j=await r.json();if(!r.ok||j.error)throw Error(j.error||'Central merge failed');await fetchCentral();const m=j.merge||{},wi=m.workforce||{},ix=m.interaction||{};msg(`Upload successful. Workforce: ${login.length?`${wi.inserted||0} inserted, ${wi.updated||0} updated`:'not uploaded'}. Interaction: ${customer.length?`${ix.inserted||0} inserted, ${ix.updated||0} updated`:'not uploaded'}. Existing data not uploaded remains preserved.`,'success');setTimeout(()=>{try{W.go('/overview')}catch(e){}},900)}
function wire(){W=iframe.contentWindow;W.startUpload=upload;W.processFiles=upload;W.__centralIncrementalUpload=upload;W.document.addEventListener('click',e=>{const b=e.target.closest&&e.target.closest('#centralUploadBtn');if(b){e.preventDefault();e.stopImmediatePropagation();upload().catch(err=>{console.error(err);msg('Upload failed: '+err.message,'dangerbox')})}},true)}
const iframe=document.getElementById('app');iframe.addEventListener('load',()=>{wire();new MutationObserver(()=>{if(W&&W.document.getElementById('centralUploadBtn')){const b=W.document.getElementById('centralUploadBtn');b.textContent='Process & Merge Centrally';}}).observe(iframe.contentDocument.body,{childList:true,subtree:true})});
})();
